---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny   
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(leaflet)
library(tidyverse)
library(plotly)
library(readxl)      
library(tidyverse)
library(ggplot2)
library(lubridate)
library(grid)
library(zoo)
library(shinyWidgets)
library(shiny)
options(shiny.sanitize.errors = FALSE)
```



```{r}
setwd("C:/Users/Mohamed/Desktop/Dashboard")
Alex_Detailed <- "Alex Water Detailed.xlsx"
year_2016 <- read_excel(Alex_Detailed, 1)
year_2017 <- read_excel(Alex_Detailed, 2)
year_2018 <- read_excel(Alex_Detailed, 3)
year_2019 <- read_excel(Alex_Detailed, 4)

#Stote duplicate columns in other df
complain_types <- unique(year_2019[, c('ComplainTypeID','ComplainTypeName')])
complain_classes <- unique(year_2019[, c('ComplainClassID','ComplainClassName')])
Sources <-  unique(year_2019[, c('SourceID...41','SourceName')]) %>% 
  rename(SourceID = SourceID...41)

Sectors <-  select(read_excel("Alex Water Area Sector Town.xlsx", 2),c("SectorID","SectorName"))
towns <- unique(select(year_2019 ,c("TownID","SectorID","TownName")))
Areas <-  select(read_excel("Alex Water Area Sector Town.xlsx", 1),c("AreaID","AreaName","LocationID","TownID","SectorID"))
#Location code 323 not found
Locations <-   select(read_excel("Alex Water Area Sector Town.xlsx", 4), c("LocationID","LocationName"))

## CONVERTING TO FACTORS
Sectors$SectorID <- as.factor(Sectors$SectorID)

towns$SectorID <- as.factor(towns$SectorID)
towns$TownID <- as.factor(towns$TownID)

Areas$SectorID <- as.factor(Areas$SectorID)
Areas$TownID <- as.factor(Areas$TownID)
Areas$LocationID <- as.factor(Areas$LocationID)
Areas$AreaID <- as.factor(Areas$AreaID)

#Drop duplicate columns and columns full of NULLS
#dropped LocationCode and  because we have another LocationID so we don't need it 
# we don't have cases dataset so we droped CaseID
# it's too hard to make filterations and decisions using Street names and notes because it has alot of typing mistakes
drops1 <- c("MainStreetID", "LandMarkID","LocationTypeID","LocationCode", 'AreaCode',
           'ComplainTypeName','ComplainClassName',"SourceName","SectorName","TownName","AreaName","AreaCode",
           "CaseID", "HomeNumber", "SideStreet", "MainStreet", "Notes" , "Date_Time2")
drops2 <- c("Quarter","Month Value")
## Converting columns of double type to factor type
edited_col <- c("FloorNumberID","IsClosed","IsReported","IsReplied","IsFinalReplied","IsFollwed",
                "IsReturned","SourceID","AreaID","SectorID","TownID",
                "LocationID","ComplainTypeID","ComplainClassID","SourceID")
#create new columns and drop duplicate column
#extract companyID from completeNumber column then drop it because all other info in it we already have

year_2019 %>%
  select(- drops1,- ...10) %>%
  mutate(Company_ID = substr(CompleteNumber, 1, 1)) %>%
  mutate(Season = quarters(Date_Time),Year=year(Date_Time)) %>% 
  select(- CompleteNumber) %>% 
  select(- SourceID...41) %>% 
  rename(SourceID = SourceID...20) %>% 
  mutate_at( vars(edited_col), funs(as.factor)) %>%
  mutate_at(vars("AppendTo"), funs(as.numeric)) -> clean_year_2019


year_2018 %>%
  select(- drops1) %>%
  mutate(Company_ID = substr(CompleteNumber, 1, 1)) %>%
  mutate(Season = quarter(Date_Time),Year=year(Date_Time)) %>% 
  select(- CompleteNumber) %>% 
  select(- SourceID...19) %>% 
  rename(SourceID = SourceID...40) %>% 
  mutate_at( vars(edited_col), funs(as.factor)) %>%
  mutate_at(vars("AppendTo"), funs(as.numeric)) -> clean_year_2018



year_2017 %>%
  select(- drops1) %>%
  mutate(Company_ID = substr(CompleteNumber, 1, 1)) %>%
  mutate(Season = quarter(Date_Time),Year=year(Date_Time)) %>% 
  select(- CompleteNumber) %>% 
  select(- SourceID...40) %>% 
  rename(SourceID=SourceID...19) %>% 
  mutate_at( vars(edited_col), funs(as.factor)) %>% 
  mutate_at(vars("AppendTo"), funs(as.numeric)) -> clean_year_2017


year_2016 %>%
  select(- drops1) %>%
  mutate(Company_ID = substr(CompleteNumber, 1, 1)) %>%
  mutate(Season = quarter(Date_Time), Year=year(Date_Time)) %>% 
  select(- CompleteNumber) %>% 
  select(- SourceID2) %>% 
  select(- drops2) %>% 
  mutate_at( vars(edited_col), funs(as.factor)) %>%
  mutate_at(vars("AppendTo"), funs(as.numeric)) -> clean_year_2016


All_Years <- rbind(clean_year_2019,rbind(clean_year_2018,rbind(clean_year_2017,rbind(clean_year_2016))))

X_Y <- c("X","Y", 'ComplainClassID', 'Date_Time')
COO <- select(All_Years, X_Y)
COO$X <- as.numeric(COO$X)
COO$Y <- as.numeric(COO$Y)
COO <- na.omit(COO)
All_Years <- select(All_Years,- c("X","Y"))

## adding locationid column to broken data using join
broken_2017 <- read_excel('Book1.xlsx', 1)
broken_2018 <- read_excel('Book2.xlsx', 1)
broken_2019 <- read_excel('Book3.xlsx', 1)

broken_2018 %>% 
  inner_join(select(broken_2017, LocationID, LocationName) %>% rename(LocationID1 = LocationID)) %>%
  mutate(if(is.na(LocationID)){ LocationID1} else { LocationID}) %>%
  select(-c("LocationID", "LocationID1", "LocationName")) %>%
  rename(LocationID = `if (...) NULL`) -> broken_2018

broken_2019 %>% 
  inner_join(select(broken_2017, LocationID, LocationName) %>% rename(LocationID1 = LocationID)) %>%
  mutate(if(is.na(LocationID)){ LocationID1} else { LocationID}) %>%
  select(-c("LocationID", "LocationID1", "LocationName")) %>%
  rename(LocationID = `if (...) NULL`) -> broken_2019

broken_2017$CaseType <- broken_2019$CaseType[1]
#############
Names <- names(broken_2018)                        
broken_2019 <- unique(select(broken_2019, Names))
broken_2017 <- unique(select(broken_2017, Names))
broken_2018 <- unique(broken_2018)
all_broken <- rbind(broken_2019, rbind(broken_2018 ,broken_2017))
##############
complain_classes$ComplainClassID   <- as.factor(complain_classes$ComplainClassID)
complain_types$ComplainTypeID <- as.factor(complain_types$ComplainTypeID)
#############
#Group all brokens in one dataset and make new date columns
remove <- c("BrokeTime", "CloseTime", "FixDate", "OpenTime")
all_broken %>% 
  mutate(StartFix = ymd_hm(paste(BrokeTime, CloseTime)),
         EndFix = ymd_hm(paste(FixDate, OpenTime))) %>%
          select(- remove) -> all_broken

all_broken$CaseType <- as.factor(all_broken$CaseType)
mutate(all_broken, MeanTime = as.integer(EndFix - StartFix) / 60) -> all_broken
all_broken$LocationID <- as.factor(all_broken$LocationID)
levels(all_broken$LocationID) <- c("3"  , "43" ,  "83"  ,
                                   "123" , "163" , "203"  ,
                                   "243" , "363" , "283" ,
                                   "443" , "483" , "523"  ,"1803")
all_broken$LocationID[(all_broken$LocationID == 263)] <- 363
Locations$LocationID <- as.factor(Locations$LocationID)

## reading plant avg
plant_Avg <- "classified Plant Average Intakes Outlet WQI Final Results-2016-2019.xlsx"
Intake_WQI <- read_excel(plant_Avg,1)
Intake_WQI$Date <-ymd(paste(Intake_WQI$year,"-",Intake_WQI$month,"- 01"))
yq <- as.yearqtr(as.yearmon(Intake_WQI$Date, "%m/%d/%Y") + 1/12)
Intake_WQI$Season <- factor(format(yq, "%q"), levels = 1:4, 
                labels = c("winter", "spring", "summer", "fall"))

Outlet_WQI <- read_excel(plant_Avg,2) 
Outlet_WQI$Date <-ymd(paste(Outlet_WQI$year,"-",Outlet_WQI$month,"- 01"))
yq <- as.yearqtr(as.yearmon(Outlet_WQI$Date, "%m/%d/%Y") + 1/12)
Outlet_WQI$Season <- factor(format(yq, "%q"), levels = 1:4, 
                labels = c("winter", "spring", "summer", "fall"))

Intakes <-  read_excel(plant_Avg,3)
Outlets <-  read_excel(plant_Avg,4)

Intakes$Total_Coliform <- as.numeric(Intakes$Total_Coliform)
Intakes$Total_Algae_Count <- as.numeric(Intakes$Total_Algae_Count)

Outlets$Total_Coliform <- as.numeric(Outlets$Total_Coliform)
Outlets$Total_Algae_Count <- as.numeric(Outlets$Total_Algae_Count)


 
Water_types <- filter(clean_year_2019, ComplainClassID == "1") %>%
  select(ComplainTypeID) %>% inner_join(complain_types)

all_broken$LocationID <- as.factor(all_broken$LocationID)
levels(complain_types$ComplainTypeID) <- levels(All_Years$ComplainTypeID)

```


OverAll 
==================================================================

Column{data-width = 100 .sidebar}
-----------------------------------------------------------------------

```{r}

selectInput("Town",
            label = "Select the Town",
            choices = c("جميع الأحياء" = "0", "حى العامرية اول" = "3", "حى المنتزة اول" = "83",
                        "حى المنتزة ثان" = "123", "	حى شرق اول" = "163",
                        "برج العرب" = "203", "حى العامرية ثان" = "243",
                        "حى غرب" = "283", "حى وسط اول" = "323",
                        "حى شرق ثان" = "363", "حى وسط ثان" = "403"),
            
            
            selected = c("0"))

selectInput("Location",
            label = "Select the Location",
            choices = c("ابو قير (حى المنتزة)" = "3",
 "الابراهيمية (حى وسط)" = "43",
 "البلد ومحرم بك (حى وسط - الجمرك)" = "83",
 "الرمل (حى شرق)" = "123",
 "العامرية (حى العامريه)" = "163",
 "العـجـمــى (حى غرب - العامريه)" = "203",
 "القبارى(حى غرب )" = "243",
 "المندرة (حى المنتزة)" = "283",
 "الميناء (حى الجمرك)" = "323",
 "النزهه (حى وسط)" = "363",
 "النوبارية(حى العامرية)" = "403",
 "برج العرب الجديد (حى برج العرب)" = "443",
 "برج العرب القديم (حى برج العرب)" = "483",
 "سيـدى بــشر (حى المنتزة - شرق)" = "523",
 "الساحل / أكتوبر  (حى غرب - العامريه)" = "1803",
 "جميع محطات المياة" = "0"),
            
            
            selected = c("0"))


radioButtons("Class",
            label = "Select the class",
            choices = c("All" = "0", "Water" = "1", "Bills" = "3","Quality" = "4", "Projects" = "7", "Not Related" = "6"), selected = c("0"))

dateInput("Start_Date", 'Select Start Date', value = "2016-01-01")

dateInput('End_Date', 'Select End Date', value = "2019-12-31")

new_all <- reactive({
  if (input$Class == "3") {K <- All_Years %>% filter(ComplainClassID == "3")
  } else if (input$Class == "1") {K <- All_Years %>% filter(ComplainClassID == "1")
  } else if (input$Class == "4") {K <- All_Years %>% filter(ComplainClassID == "4")
  } else if (input$Class == "6") {K <- All_Years %>% filter(ComplainClassID == "6")
  } else if (input$Class == "7") {K <- All_Years %>% filter(ComplainClassID == "7")
  } else {K <- All_Years}
  K<- K %>%
         filter(date(Date_Time) <= input$End_Date,
                date(Date_Time) >= input$Start_Date) 
  
  if (input$Town == "3") {K <- K %>% filter(TownID == "3")
  } else if (input$Town == "83") {K <- K %>% filter(TownID == "83")
  } else if (input$Town == "123") {K <- K %>% filter(TownID == "123")
  } else if (input$Town == "163") {K <- K %>% filter(TownID == "163")
  } else if (input$Town == "203") {K <- K %>% filter(TownID == "203")
  } else if (input$Town == "243") {K <- K %>% filter(TownID == "243")
  } else if (input$Town == "283") {K <- K %>% filter(TownID == "283")
  } else if (input$Town == "323") {K <- K %>% filter(TownID == "323")
  } else if (input$Town == "363") {K <- K %>% filter(TownID == "363")
  } else if (input$Town == "403") {K <- K %>% filter(TownID == "403")
  } else {K <- K}
  
  
  if (input$Location == "3") {K <- K %>% filter(LocationID == "3")
  } else if (input$Location == "43") {K <- K %>% filter(LocationID == "43")
  } else if (input$Location == "83") {K <- K %>% filter(LocationID == "83")
  } else if (input$Location == "123") {K <- K %>% filter(LocationID == "123")
  } else if (input$Location == "163") {K <- K %>% filter(LocationID == "163")
  } else if (input$Location == "203") {K <- K %>% filter(LocationID == "203")
  } else if (input$Location == "243") {K <- K %>% filter(LocationID == "243")
  } else if (input$Location == "283") {K <- K %>% filter(LocationID == "283")
  } else if (input$Location == "323") {K <- K %>% filter(LocationID == "323")
  } else if (input$Location == "363") {K <- K %>% filter(LocationID == "363")
  } else if (input$Location == "403") {K <- K %>% filter(LocationID == "403")
  } else if (input$Location == "443") {K <- K %>% filter(LocationID == "443")
  } else if (input$Location == "483") {K <- K %>% filter(LocationID == "483")
  } else if (input$Location == "523") {K <- K %>% filter(LocationID == "523")
  } else if (input$Location == "1803") {K <- K %>% filter(LocationID == "1803")
  } else {K <- K}
  
  
  
    K
  
  })
  
  
  
 


```


Column {data-width=900 .tabset}
-------------------------------------------------------------------------


### Complains over Time


```{r}
renderPlot({new_all() %>%
  merge(y = Sources, by = 'SourceID', all = TRUE) %>%
    mutate(date = date(Date_Time)) %>% 
    group_by(date) %>%
    summarize(num_of_complains = n()) %>%
    ggplot(aes(x = date, y = num_of_complains, color = factor(year(date)))) +
    geom_line() + 
    labs(title = "Complains over Time", x = "Date", y = "Num of Complains", color = "Year") 
      })

```





### Percentage of Closed/NonClosed complains

```{r}

renderPlot({
  new_all() %>%
  filter(!is.na(IsClosed)) %>% 
  group_by(IsClosed) %>% 
  summarise(no_of_closed= n()) %>% 
  
  ggplot(mapping = aes(x = IsClosed , y = no_of_closed, fill= factor(IsClosed))) +
  geom_bar(stat="identity",width = 1, show.legend = FALSE)+
 geom_text(aes(label=paste(round(no_of_closed / sum(no_of_closed) * 100, 1), "%")),position = position_stack(vjust = .5), size = 3.5, color = "black")+
  theme_minimal()+
 labs(x = "Closed & non closed cases", y ="Number of Comp_closed_Non",title = "Number of complain per class ", fill = "ComplainClassID' IDs") +
   scale_x_discrete(labels=c('0' = "Not Closed", '1' = "Closed"))  +
  theme(legend.position = "none") 
  })
```



Water 
==================================================================

Column{data-width = 100 .sidebar}
-----------------------------------------------------------------------


```{r}
selectInput("Locations",
            label = "Select the Location",
            choices = c("ابو قير (حى المنتزة)" = "3",
 "الابراهيمية (حى وسط)" = "43",
 "البلد ومحرم بك (حى وسط - الجمرك)" = "83",
 "الرمل (حى شرق)" = "123",
 "العامرية (حى العامريه)" = "163",
 "العـجـمــى (حى غرب - العامريه)" = "203",
 "القبارى(حى غرب )" = "243",
 "المندرة (حى المنتزة)" = "283",
 "الميناء (حى الجمرك)" = "323",
 "النزهه (حى وسط)" = "363",
 "النوبارية(حى العامرية)" = "403",
 "برج العرب الجديد (حى برج العرب)" = "443",
 "برج العرب القديم (حى برج العرب)" = "483",
 "سيـدى بــشر (حى المنتزة - شرق)" = "523",
 "الساحل / أكتوبر  (حى غرب - العامريه)" = "1803",
 "جميع محطات المياة" = "0"),
            selected = c("0"))



selectInput("Typee",
        label = "Select the Type of complain",
        choices = c("انقطاع"= "5",
                    "استفسار مياه"= "8",
                    "تسرب مياه / كسر بالخارج"= "3",
                    "ضعف مياه"= "6",
                    "	استعجال مياه"= "13",
                    "جميع الفئات"= "0"),
            selected = c("0"),
            multiple = T)

  

selectInput("Case",
        label = "Select the Type of Case",
        choices = c(unique(broken_2019$CaseType)),
            multiple = T)

dateInput("StartDate1", 'Select Start Date', value = "2016-01-01")

dateInput('EndDate1', 'Select End Date', value = "2019-12-31")



  
  

new_years <- reactive({
   
   Ka <- All_Years %>% filter(ComplainClassID == "1")
   
   Ka<- Ka %>%
         filter(date(Date_Time) <= input$EndDate1,
                date(Date_Time) >= input$StartDate1)
   
  if (input$Locations == "3") {Ka <- Ka %>% filter(LocationID == "3")
  } else if (input$Locations == "43") {Ka <- Ka %>% filter(LocationID == "43")
  } else if (input$Locations == "83") {Ka <- Ka %>% filter(LocationID == "83")
  } else if (input$Locations == "123") {Ka <- Ka %>% filter(LocationID == "123")
  } else if (input$Locations == "163") {Ka <- Ka %>% filter(LocationID == "163")
  } else if (input$Locations == "203") {Ka <- Ka %>% filter(LocationID == "203")
  } else if (input$Locations == "243") {Ka <- Ka %>% filter(LocationID == "243")
  } else if (input$Locations == "283") {Ka <- Ka %>% filter(LocationID == "283")
  } else if (input$Locations == "323") {Ka <- Ka %>% filter(LocationID == "323")
  } else if (input$Locations == "363") {Ka <- Ka %>% filter(LocationID == "363")
  } else if (input$Locations == "403") {Ka <- Ka %>% filter(LocationID == "403")
  } else if (input$Locations == "443") {Ka <- Ka %>% filter(LocationID == "443")
  } else if (input$Locations == "483") {Ka <- Ka %>% filter(LocationID == "483")
  } else if (input$Locations == "523") {Ka <- Ka %>% filter(LocationID == "523")
  } else if (input$Locations == "1803") {Ka <- Ka %>% filter(LocationID == "1803")
  } else {Ka <- Ka}
   
  if (as.character(input$Typee) == "0") {Ka <- Ka
  } else {Ka <- Ka %>% filter(ComplainTypeID %in% c(input$Typee))}
   
  Ka
 })

new_brokens <- reactive({
      H <- filter(all_broken ,CaseType %in% input$Case)
                   
      if (input$Locations == "3") {H <- H %>% filter(LocationID == "3")
  } else if (input$Locations == "43") {H <- H %>% filter(LocationID == "43")
  } else if (input$Locations == "83") {H <- H %>% filter(LocationID == "83")
  } else if (input$Locations == "123") {H <- H %>% filter(LocationID == "123")
  } else if (input$Locations == "163") {H <- H %>% filter(LocationID == "163")
  } else if (input$Locations == "203") {H <- H %>% filter(LocationID == "203")
  } else if (input$Locations == "243") {H <- H %>% filter(LocationID == "243")
  } else if (input$Locations == "283") {H <- H %>% filter(LocationID == "283")
  } else if (input$Locations == "323") {H <- H %>% filter(LocationID == "323")
  } else if (input$Locations == "363") {H <- H %>% filter(LocationID == "363")
  } else if (input$Locations == "403") {H <- H %>% filter(LocationID == "403")
  } else if (input$Locations == "443") {H <- H %>% filter(LocationID == "443")
  } else if (input$Locations == "483") {H <- H %>% filter(LocationID == "483")
  } else if (input$Locations == "523") {H <- H %>% filter(LocationID == "523")
  } else if (input$Locations == "1803") {H <- H %>% filter(LocationID == "1803")
  } 
  H<- H %>%
         filter(date(StartFix) <= input$EndDate1,
                date(StartFix) >= input$StartDate1) 
                            
  H
 })

```
 
 
Column {data-width=900 .tabset}
-------------------------------------------------------------------------


### Water Complain class
```{r}
renderPlot({
    new_years() %>%
    merge(y=complain_types,by="ComplainTypeID",all=TRUE) %>%
    group_by(ComplainTypeID, ComplainTypeName) %>%
    summarize(num_of_complains = n()) %>%
    ggplot(aes(x = ComplainTypeName, y = num_of_complains, fill = ComplainTypeName)) +
    geom_col() +
    labs(title = "Complain num for each type in water class", x = "Complain type", y = "Num of Complains") +
   theme(axis.text.x = element_text(angle = 90, size =  12, face = 90))  +
  theme(legend.position = "none") 
   })
```



### Percentage of Closed/NonClosed complains

```{r}

renderPlot({
  new_brokens() %>%
   group_by(CaseType) %>%
   summarise(num_of_cases = n()) %>%
   arrange(desc(num_of_cases)) %>%
   ggplot(aes(x = CaseType , y = num_of_cases, fill = CaseType)) +
  geom_col() +
  theme(legend.position = "none") 
  
  })

```


Bills 
==================================================================

Column{data-width = 100 .sidebar}
-----------------------------------------------------------------------


```{r}
selectInput("Locations3",
            label = "Select the Location",
            choices = c("ابو قير (حى المنتزة)" = "3",
 "الابراهيمية (حى وسط)" = "43",
 "البلد ومحرم بك (حى وسط - الجمرك)" = "83",
 "الرمل (حى شرق)" = "123",
 "العامرية (حى العامريه)" = "163",
 "العـجـمــى (حى غرب - العامريه)" = "203",
 "القبارى(حى غرب )" = "243",
 "المندرة (حى المنتزة)" = "283",
 "الميناء (حى الجمرك)" = "323",
 "النزهه (حى وسط)" = "363",
 "النوبارية(حى العامرية)" = "403",
 "برج العرب الجديد (حى برج العرب)" = "443",
 "برج العرب القديم (حى برج العرب)" = "483",
 "سيـدى بــشر (حى المنتزة - شرق)" = "523",
 "الساحل / أكتوبر  (حى غرب - العامريه)" = "1803",
 "جميع محطات المياة" = "0"),
            selected = c("0"))



selectInput("Typee4",
        label = "Select the Type of complain",
        choices = c("ارتفاع فاتورة" = "17",
                    "ابلاغ قراءة" = "18",
                    "عدم مرور محصل" = "20",
                    "عدم مرور قارئ" = "21",
                    "جميع الشكاوي" = "0"),
            selected = c("0"),
            multiple = T)




dateInput("StartDate3", 'Select Start Date', value = "2016-01-01")

dateInput('EndDate3', 'Select End Date', value = "2019-12-31")



  
  

new_years4 <- reactive({
   
   Ka4 <- All_Years %>% filter(ComplainClassID == "3")
   
   Ka4<- Ka4 %>%
         filter(date(Date_Time) <= input$EndDate3,
                date(Date_Time) >= input$StartDate3)
   
  if (input$Locations3 == "3") {Ka4 <- Ka4 %>% filter(LocationID == "3")
  } else if (input$Locations3 == "43") {Ka4 <- Ka4 %>% filter(LocationID == "43")
  } else if (input$Locations3 == "83") {Ka4 <- Ka4 %>% filter(LocationID == "83")
  } else if (input$Locations3 == "123") {Ka4 <- Ka4 %>% filter(LocationID == "123")
  } else if (input$Locations3 == "163") {Ka4 <- Ka4 %>% filter(LocationID == "163")
  } else if (input$Locations3 == "203") {Ka4 <- Ka4 %>% filter(LocationID == "203")
  } else if (input$Locations3 == "243") {Ka4 <- Ka4 %>% filter(LocationID == "243")
  } else if (input$Locations3 == "283") {Ka4 <- Ka4 %>% filter(LocationID == "283")
  } else if (input$Locations3 == "323") {Ka4 <- Ka4 %>% filter(LocationID == "323")
  } else if (input$Locations3 == "363") {Ka4 <- Ka4 %>% filter(LocationID == "363")
  } else if (input$Locations3 == "403") {Ka4 <- Ka4 %>% filter(LocationID == "403")
  } else if (input$Locations3 == "443") {Ka4 <- Ka4 %>% filter(LocationID == "443")
  } else if (input$Locations3 == "483") {Ka4 <- Ka4 %>% filter(LocationID == "483")
  } else if (input$Locations3 == "523") {Ka4 <- Ka4 %>% filter(LocationID == "523")
  } else if (input$Locations3 == "1803") {Ka4 <- Ka4 %>% filter(LocationID == "1803")
  } else {Ka4 <- Ka4}
   
  if (as.character(input$Typee4) == "0") {Ka4 <- Ka4
  } else {Ka4 <- Ka4 %>% filter(ComplainTypeID %in% c(input$Typee4))}
   
  Ka4
 })
```

Column {data-width=900}
-------------------------------------------------------------------------


### Bills Complain class
```{r}
renderPlot({
    new_years4() %>%
    merge(y=complain_types,by="ComplainTypeID",all=TRUE) %>%
    group_by(ComplainTypeID, ComplainTypeName) %>%
    summarize(num_of_complains = n()) %>%
    ggplot(aes(x = ComplainTypeName, y = num_of_complains, fill = ComplainTypeName)) +
    geom_col() +
    labs(title = "Complain num for each type in water class", x = "Complain type", y = "Num of Complains") +
   theme(axis.text.x = element_text(angle = 90, size =  12, face = 90))  +
  theme(legend.position = "none") 
   })
```


Quality 
==================================================================

Column{data-width = 100 .sidebar}
-----------------------------------------------------------------------


```{r}
selectInput("Locations5",
            label = "Select the Location",
            choices = c("ابو قير (حى المنتزة)" = "3",
 "الابراهيمية (حى وسط)" = "43",
 "البلد ومحرم بك (حى وسط - الجمرك)" = "83",
 "الرمل (حى شرق)" = "123",
 "العامرية (حى العامريه)" = "163",
 "العـجـمــى (حى غرب - العامريه)" = "203",
 "القبارى(حى غرب )" = "243",
 "المندرة (حى المنتزة)" = "283",
 "الميناء (حى الجمرك)" = "323",
 "النزهه (حى وسط)" = "363",
 "النوبارية(حى العامرية)" = "403",
 "برج العرب الجديد (حى برج العرب)" = "443",
 "برج العرب القديم (حى برج العرب)" = "483",
 "سيـدى بــشر (حى المنتزة - شرق)" = "523",
 "الساحل / أكتوبر  (حى غرب - العامريه)" = "1803",
 "جميع محطات المياة" = "0"),
            selected = c("0"))



selectInput("Typee5",
        label = "Select the Type of complain",
        choices = c("ارتفاع فاتورة" = "17",
                    "ابلاغ قراءة" = "18",
                    "عدم مرور محصل" = "20",
                    "عدم مرور قارئ" = "21",
                    "جميع الشكاوي" = "0"),
            selected = c("0"),
            multiple = T)




dateInput("StartDate5", 'Select Start Date', value = "2016-01-01")

dateInput('EndDate5', 'Select End Date', value = "2019-12-31")



  
  

new_years5 <- reactive({
   
   Ka5 <- All_Years %>% filter(ComplainClassID == "4")
   
   Ka5<- Ka5 %>%
         filter(date(Date_Time) <= input$EndDate5,
                date(Date_Time) >= input$StartDate5)
   
  if (input$Locations5 == "3") {Ka5 <- Ka5 %>% filter(LocationID == "3")
  } else if (input$Locations5 == "43") {Ka5 <- Ka5 %>% filter(LocationID == "43")
  } else if (input$Locations5 == "83") {Ka5 <- Ka5 %>% filter(LocationID == "83")
  } else if (input$Locations5 == "123") {Ka5 <- Ka5 %>% filter(LocationID == "123")
  } else if (input$Locations5 == "163") {Ka5 <- Ka5 %>% filter(LocationID == "163")
  } else if (input$Locations5 == "203") {Ka5 <- Ka5 %>% filter(LocationID == "203")
  } else if (input$Locations5 == "243") {Ka5 <- Ka5 %>% filter(LocationID == "243")
  } else if (input$Locations5 == "283") {Ka5 <- Ka5 %>% filter(LocationID == "283")
  } else if (input$Locations5 == "323") {Ka5 <- Ka5 %>% filter(LocationID == "323")
  } else if (input$Locations5 == "363") {Ka5 <- Ka5 %>% filter(LocationID == "363")
  } else if (input$Locations5 == "403") {Ka5 <- Ka5 %>% filter(LocationID == "403")
  } else if (input$Locations5 == "443") {Ka5 <- Ka5 %>% filter(LocationID == "443")
  } else if (input$Locations5 == "483") {Ka5 <- Ka5 %>% filter(LocationID == "483")
  } else if (input$Locations5 == "523") {Ka5 <- Ka5 %>% filter(LocationID == "523")
  } else if (input$Locations5 == "1803") {Ka5 <- Ka5 %>% filter(LocationID == "1803")
  } else {Ka5 <- Ka5}
   
  if (as.character(input$Typee5) == "0") {Ka5 <- Ka5
  } else {Ka5 <- Ka5 %>% filter(ComplainTypeID %in% c(input$Typee5))}
   
  Ka5
 })
```

Column {data-width=900}
-------------------------------------------------------------------------


### Bills Complain class
```{r}
renderPlot({
    new_years5() %>%
    merge(y=complain_types,by="ComplainTypeID",all=TRUE) %>%
    group_by(ComplainTypeID, ComplainTypeName) %>%
    summarize(num_of_complains = n()) %>%
    ggplot(aes(x = ComplainTypeName, y = num_of_complains, fill = ComplainTypeName)) +
    geom_col() +
    labs(title = "Complain num for each type in water class", x = "Complain type", y = "Num of Complains") +
   theme(axis.text.x = element_text(angle = 90, size =  12, face = 90))  +
  theme(legend.position = "none") 
   })
```


Map
==================================================================


Column {data-width = 1000}
-----------------------------------------------------------------------

### Alex Map

```{r}
leaflet() %>%
  addTiles() %>%
  addMarkers(lat = COO$X, lng = COO$Y)
```


